### ISSUE TITLE
Without StrictMode / In Production Mode onColumnSizingChange does not return any values during resize

### ISSUE THREAD

**Issue by bjoe87** [TanStack/table#4479] opened 2022-10-24 19:21 UTC
### Describe the bug

No values are returned when using onColumnSizing during the resize event when app is not wrapped with strictmode.
Provided sandbox is based of https://tanstack.com/table/v8/docs/examples/react/column-sizing 

Uncomment StrictMode at the bottom to get column resizing working.

### Your minimal, reproducible example

https://codesandbox.io/s/dazzling-lake-pr2n28?file=/src/main.tsx

### Steps to reproduce

1. go to https://codesandbox.io/s/dazzling-lake-pr2n28?file=/src/main.tsx
2. Try to resize any column

### Expected behavior

Column should resize. The values for onColumnSizingChange should be passed to the updater.

### Platform

- macOS Monterey: 12.6
- Chrome 106.0.5249.119

### react-table version

v8.5.15

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by talatkuyuk** [comment] 2022-10-25 12:58
It is very strange. **The resizing feature** **has broken** in my nextjs app a week ago. I tried to figure it out. It screwed my several days.

Then I see this issue. Yes, `reactStrictMode: false` in the `next.config.js`.

Then I turned it into `true`, then resizing started to work. But I would like to keep it false, since I haven't migrated the useEffects in my app according to React18 yet.

**Comment by bjoe87** [comment] 2022-11-29 15:26
Was able to look into it today. The underlying problem is the newColumnSizing variable does not contain what gets calculated within the updater. The quick fix is to just move newColumnSizing outside of updateOffset function. (I confirmed this and it works) https://github.com/TanStack/table/blob/main/packages/table-core/src/features/ColumnSizing.ts#L229

**Comment by rdecoito** [comment] 2022-12-16 20:18
Looks like https://github.com/TanStack/table/pull/4606 reverted the above MR, but it doesn't seem as if there was any explanation why this happened. I'm having this problem in my production build, and I can replicate the problem easily with v8.7.3 (my project is using v8.7.0, so it's present on that version as well). I just tested it with a minimum reproducible example, and the issue was definitely fixed in v8.7.2 by the above MR, so I'd really love to know why the fix was reverted.

I spent a long time migrating our rather large codebase to v8 only to discover this bug once I pushed it up to our dev environment, so that's been rather frustrating.


Side note, in the spirit of documentation I want to place my observations here. I've been able to consistently see the following behavior, and you can verify this in OP's sandbox example:

1. If you click and drag the resize grip at a normal speed (casually click, drag, let go) you will not see the column size update. However,
2. The column size _WILL_ update if you let go of the mouse button extremely quickly after moving the mouse. So mouse down on the resize grip and hold, then flick your wrist and very quickly let go of the mouse button. You'll see the column size update.

The second behavior is consistent, as long as you flick your wrist and let go of the button within a certain amount of time (maybe half a second? hard to tell). This makes me think it could be down to some sort of mount/update condition, or a debounce, or something else.


Anyway, can we get some information about what happened with the fix? Thanks y'all.

**Comment by KevinVandy** [comment] 2022-12-17 01:11
Sorry for not being clear on this. Somehow, v8.7.2 introduced some build errors in some next.js projects. I first reverted this to rule out that PR as a possibility. This will be added back in soon.

**Comment by KevinVandy** [comment] 2022-12-18 20:41
The fix was returned in v8.7.4 as it was not the cause of build errors

**Closed by KevinVandy** 2022-12-18 20:41 UTC
