### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'filter') Tanstack table (React)

### ISSUE THREAD

**Issue by jrhager84** [TanStack/table#4610] opened 2022-12-18 10:48 UTC
### Describe the bug

I have a working Tanstack table in dev mode. However, the minute I try to push it to prod, I get this error: 

```
framework-3b5a00d5d7e8d93b.js:9 TypeError: Cannot read properties of undefined (reading 'filter')
    at 338-40b21a5eb2cada72.js:42:10338
    at Object.getVisibleLeafColumns (338-40b21a5eb2cada72.js:39:249)
    at 338-40b21a5eb2cada72.js:42:5838
    at Object.getHeaderGroups (338-40b21a5eb2cada72.js:39:249)
    at u (index-ef857841339be48b.js:1:1605)
    at ak (framework-3b5a00d5d7e8d93b.js:9:60917)
    at i (framework-3b5a00d5d7e8d93b.js:9:119475)
    at oD (framework-3b5a00d5d7e8d93b.js:9:99114)
    at framework-3b5a00d5d7e8d93b.js:9:98981
    at oO (framework-3b5a00d5d7e8d93b.js:9:98988)
a9 @ framework-3b5a00d5d7e8d93b.js:9
main-f2e125da23ccdc4a.js:1 TypeError: Cannot read properties of undefined (reading 'filter')
    at 338-40b21a5eb2cada72.js:42:10338
    at Object.getVisibleLeafColumns (338-40b21a5eb2cada72.js:39:249)
    at 338-40b21a5eb2cada72.js:42:5838
    at Object.getHeaderGroups (338-40b21a5eb2cada72.js:39:249)
    at u (index-ef857841339be48b.js:1:1605)
    at ak (framework-3b5a00d5d7e8d93b.js:9:60917)
    at i (framework-3b5a00d5d7e8d93b.js:9:119475)
    at oD (framework-3b5a00d5d7e8d93b.js:9:99114)
    at framework-3b5a00d5d7e8d93b.js:9:98981
    at oO (framework-3b5a00d5d7e8d93b.js:9:98988)
$ @ main-f2e125da23ccdc4a.js:1
main-f2e125da23ccdc4a.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

### Your minimal, reproducible example

https://stackblitz.com/edit/nextjs-pf2fbn?file=README.md

### Steps to reproduce

deploy that code anywhere, and it will fail after you add the files (works 100% in dev mode).

Github repo here -> https://github.com/jrhager84/moby-dick

Version that crashes (Cloudflare Pages) - https://moby-dick.pages.dev/

### Expected behavior

Table should render

### How often does this bug happen?

Every time

### Platform

macOS 12.6.1
Chrome (latest)

### react-table version

8.7.3

### TypeScript version

4.9.4

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by nemixe** [comment] 2022-12-18 15:57
i'm getting the same issue, for now i'm downgrading react-table to version 8.7.0

**Comment by jrhager84** [comment] 2022-12-18 16:28
> i'm getting the same issue, for now i'm downgrading react-table to version 8.7.0

You're right! 8.7.0 works great. Hopefully this report will help get it fixed 😊

Thanks!

**Comment by KevinVandy** [comment] 2022-12-18 17:44
Try v8.7.4

**Comment by izorg** [comment] 2022-12-18 19:12
Same error for me on `v8.7.4`

**Comment by KevinVandy** [comment] 2022-12-18 20:30
> Same error for me on `v8.7.4`

Ok, so this is really weird. I created a couple local repos. If you use Next.js 12.3.2 and react 17, there is no error with TanStack Table v8.7.4.

But if you use Next 13 and React 18, there is this error.

**Comment by KevinVandy** [comment] 2022-12-18 20:34
Actually I have narrowed it down to just next 13. 

But it doesn't make sense, because 8.7.0 works on next 13, but there also have been no code changes in TanStack Table between 8.7.0 and 8.7.4 that should cause this.

It's going to need even deeper investigation

**Comment by KevinVandy** [comment] 2022-12-18 21:11
For now, while this gets figured out, I made this compatibility table. Make sure no `"^"` symbol is in the table version `"@tanstack/react-table": "8.7.0",` if you are on Next 13.

| TanStack Table Version | Next.js Version | Compatible |
| --- | ----------- | - |
| 8.7.4 | 13.0.7 | ❌ |
| 8.7.4 | 12.3.4 | ✅|
| 8.7.0 | 13.0.7 | ✅|
| 8.7.0 | 12.3.4 | ✅|

**Comment by OmerWow** [comment] 2022-12-19 08:21
@izorg @jrhager84 @nemixe @KevinVandy 
I've made many tests because my production crashed too.
Turns out it's because Next.js 13 enabled SWCMinify by default, instead of Terser.
It's significantly faster and was considered stable since the release of Next.js 13 in late October, but looks like it's not fully stable yet...

Adding
```
swcMinify: false
```
to the next.config.js makes Terser the default minifier again and solves the problem.

**Comment by izorg** [comment] 2022-12-22 18:36
After Next.js 13.1.0 release, version 8.7.4 works again

**Comment by anhdd-kuro** [comment] 2022-12-23 05:57
I have the same issue
confirm upgrade to Next.js 13.1.0 fixed this problem

**Comment by ajubin** [comment] 2022-12-26 09:07
Hi, thanks for the fix.

Out of curiosity, I'd like to understand the line in next.js that causes the bug.
For that, I dug into next.js 13.1.0 release: https://github.com/vercel/next.js/releases/tag/v13.1.0

The changes that fixes the problem  seems to be this one #43983 that bumps swc, but then I don't know how to go deeper, does someone has more clue ?

**Comment by jcready** [comment] 2023-01-01 13:15
This can be closed as the issue was caused by a buggy minifier in Next.js/SWC.

**Comment by jasonzhouu** [comment] 2023-01-09 03:53
TanStack Table Version | Next.js Version | Compatible
-- | -- | --
8.7.4 | 12.3.1 | ❌
8.7.0 | 12.3.1 | ✅

**Comment by KevinVandy** [comment] 2023-01-09 04:03
@jasonzhouu 

I'm testing this locally in v8.7.6 which I just released a few minutes ago and it might be fixed... Even with next 13.0. Will leave this open until others can verify.

**Comment by jcready** [comment] 2023-01-09 10:27
This is a bug in next.js. This issue should be closed.

**Closed** 2023-01-09 23:42 UTC
Labels: critical

**Comment by klugeradoslaw** [comment] 2024-10-25 06:58
Has anyone had the same issue on next14?
@tanstack/react-table - 8.20.5
next - 14.2.5

Is there any way to deal with this? I tried downgrade react-table to 8.7.0, but it didn't help.  But I can't downgrade next :(
