### ISSUE TITLE
Sorting ignores the initial state when enableSorting is false

### ISSUE THREAD

**Issue by ZiedHf** [TanStack/table#4324] opened 2022-08-18 17:08 UTC
### Describe the bug

React Table does not initially sort the values when enableSorting is false. 

### Your minimal, reproducible example

https://codesandbox.io/s/react-table-v8-initial-sorting-issue-mdic6x?file=/src/main.tsx

### Steps to reproduce

1- Open the example
2- Don't do anything, firstName is not sorted

### Expected behavior

the firstName column should be sorted initially

### How often does this bug happen?

Every time

### Screenshots or Videos

No need

### Platform

OS : Windows
Browser : Chrome / Firefox

### react-table version

v8.5.11

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment] 2022-08-22 13:28
I think this is expected behavior? If you disable sorting, it won't occur. Sort your data before passing it to the table.

**Comment by ZiedHf** [comment] 2022-08-22 13:45
@KevinVandy Take a look in the behavior of React Table v7. It wasn't the same.

Sorting the data in the parent component means adding another useless layer of code which. If I use a built-in sorted method and I passed an initial state I expect to see the initial state executed just after the mount then disable the possibility of sorting that column. Exactly the same as React Table v7.

**Comment by KevinVandy** [comment] 2022-10-22 01:15
Most likely going to close this issue, as it seems to be an argument with intended behavior. If you want sorting to occur, don't disable it? You can disable your sorting UI independently of this built-in `enableSorting` if that's what you need.

**Closed** 2022-10-22 01:16 UTC
Labels: wontfix

**Comment by ZiedHf** [comment] 2023-01-06 19:29
@KevinVandy oh I didn't see this issue was closed until now. And I have no clue why this is closed.

okay so, are you suggesting that the initial sortBy state of a table depends on `enableSorting` ? I don't think this is the entended behavior tbh. Please check first the version 7 of this library.

I might sort by multi columns **initially** and deactivate the sorting feature.

enableSorting = canSort() => false
But should not affect the initial state.

**Comment by KevinVandy** [comment] 2023-01-06 19:31
This was closed because it is intended behavior for v8

**Comment by ZiedHf** [comment] 2023-01-06 19:34
In that case we will have to use the same sort plugin before passing the data to the Table.

Is there a way/documentation/example that show how to use th e sort plugin ? (Especially for complex cases like : Date, Leaf columns ... etc)

**Comment by ZiedHf** [comment] 2023-01-06 20:05
This is an example using Data Grid of Material UI to sort initially by rating and disable sorting

https://codesandbox.io/s/initial-sorting-and-disable-sorting-using-data-grid-table-github-link-8cwfbw

**Comment by KevinVandy** [comment] 2023-01-06 21:55
The plugin system is removed in v8. Again, I really don't understand why you want to disable sorting but expect initial sorting to occur. The very easy and simple solution is to enable sorting, but have a separate state to disable sorting in your ui.

**Comment by ZiedHf** [comment] 2023-01-06 22:44
Yeah that's what I am using since day one, before I post this issue.

I just posted it because I thought it's a bug.

Why I thought it's not intended ?

Because many Table Libraries including (React-Table v7) mount the table with the initial state (it has a priority) then enable/disable sorting (Filter, or any other feature).

It's a matter of priority.

When we prioritize the initial state over enableSorting, there is no need to write a code like this :

```
<MyTable sorting={[{ id: 'col1', desc: false }]} enableSorting butDisableUISorting />
```

Instead we write just

```
<MyTable enableSorting sorting={[{ id: 'col1', desc: false }]} />
```
And we understand that this table will sort the data by `col1`. However it's not possible to use `toggleSorting` and getCanSort returns false.

Anyway, thanks for you time and your suggestion.
