### ISSUE TITLE
useReactTable and sorting causing infinite rerenders

### ISSUE THREAD

**Issue by JacobWeisenburger** [TanStack/table#4392] opened 2022-09-16 20:41 UTC
### Describe the bug

When I use a controlled input with `useState` and I also use `useReactTable` and I have sorting for the `name` field, then when I type in the input it causes react to rerender infinitely.

### Your minimal, reproducible example

https://github.com/JacobWeisenburger/react-table-rerenders

### Steps to reproduce

1. `npm run dev`
2. open console
3. type into input

### Expected behavior

Maybe I'm just doing something wrong here, but I feel like react shouldn't rerender more than once per keypress.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/31667350/190728477-a53b4f33-6417-4952-87d9-9853e9c9a444.png)

### Platform

- OS: Windows
- Browser: Chrome

### react-table version

8.5.13

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KyleJune** [comment] 2022-10-10 03:45
I had a similar issue. I ended up finding the cause was a useMemo that was depending on an object that was constantly changing.

**Comment by leoyli-headsup** [comment] 2022-11-07 00:01
We also faced a similar issue.  In our case, we use react-query to fetch GQL backend based on user selections to get the table data, and pass into `useReactTable`. The root cause for an infinite re-rendering was `getVisibleCells`, `getPageCount`, or calling other similar getters, which trigger the bug. We solve it by short-circuit the logic with the `loading` meta data.  But before upgrading to React 18 from 17, it was fine.

**Comment by KevinVandy** [comment] 2022-11-16 05:32
As others have said, this is almost always an issue with passing a value back to the useReactTable hook that is always changing on each render. It's not really a problem with the lib itself, but the implementation. There's a thousand ways you could run into this, but I see that you removed the repo with your example. I'm going to close this for now.

**Closed by KevinVandy** 2022-11-16 05:32 UTC

**Comment by sashulinator** [comment] 2026-03-22 07:17
Hi!
In my case the problem was with friquently changing 'data' 

```ts
const listQuery = useQuery(queryParams)
const data = React.useMemo(() => listQuery.data?.items || [], [listQuery.data?.items])
const table = Trt.useReactTable({ data, ...restTableParams })
```
